### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by SIRprise** [jacdelad/PureMondrian#1]
Hi, bin nicht im Forum registriert, aber verfolge es und habe eine Art Feature Request:
Kannst du Releases hier auf github stellen?
Es hätte den Vorteil, dass auch Leute ohne PB (die free Version kann nur 800 Zeilen Code) dein Spiel nutzen könnten. Mein eigenes Motiv ist, dass ich gerne am Feierabend mit Copy&Paste etwas probiere, aber wenn ich 3 Dateien laden muss oder Repos auschecken, ist die Hemmschwelle schon einiges größer. Im Idealfall hat es hier auch mal ein AV gescannt und in die DB eingetragen, sodass es nicht erst beim Kompilieren meckert (wenn man keine Ausnahme auf das Verzeichnis mit den bins eingestellt hat).

**Comment by jacdelad** [comment]
Hi, ja klar kann ich ein vorcompiliertes Programm bereitstellen. Allerdings nur für Windows und momentan haben wir ein Problem mit BitDefender, was falsche Alarme ausgibt. Letzteres sollte sich aber irgendwann geben.

**Comment by SIRprise** [comment]
Jetzt wollte ich gerade auf Englisch übersetzen^^ egal... Ich danke dir! :-)
